# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rbbt-study 0.2.31 ruby lib

Gem::Specification.new do |s|
  s.name = "rbbt-study"
  s.version = "0.2.31"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Miguel Vazquez"]
  s.date = "2014-08-13"
  s.description = "This gem add the study entity with suport for NGS, Microarray and other types of data"
  s.email = "miguel.vazquez@cnio.es"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "share/R/data.R",
    "share/R/plots.R"
  ]
  s.homepage = "http://github.com/mikisvaz/rbbt-study"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Genomic study entity"
end

